services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    network_mode: host

  notifer:
    depends_on:
      - redis
    build: ./notif
    restart: unless-stopped
    ports:
      - ${NOTIFER_WEBSOCKET_PORT}:${NOTIFER_WEBSOCKET_PORT}
      - ${NOTIFER_PORT}:${NOTIFER_PORT}
    environment:
      - REDIS_URL=${REDIS_URL}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - UPDATE_DELAY=${WS_UPDATE_DELAY}
      - WS_PORT=${NOTIFER_WEBSOCKET_PORT}
      - EXPRESS_PORT=${NOTIFER_PORT}
    stdin_open: true
    tty: true

volumes:
  redis_data:
