version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: cache
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/var/lib/redis
      - redis-config:/usr/local/etc/redis/redis.conf
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    expose:
      - ${REDIS_PORT}
    network_mode: host

  notifer:
    depends_on:
      - redis
    links:
      - redis
    build: ./notif
    restart: unless-stopped
    ports:
      - ${NOTIFER_WEBSOCKET_PORT}:${NOTIFER_WEBSOCKET_PORT}
      - ${NOTIFER_PORT}:${NOTIFER_PORT}
    environment:
      - REDIS_URL=redis://cache
      - UPDATE_DELAY=${WS_UPDATE_DELAY}
      - WS_PORT=${NOTIFER_WEBSOCKET_PORT}
      - EXPRESS_PORT=${NOTIFER_PORT}
    stdin_open: true
    tty: true

volumes:
  redis:
  redis-config:
