services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  redis:
    image: 'redis:alpine'
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  notifer:
    depends_on:
      - redis
    build: ./notif
    restart: on-failure
    ports:
      - ${NOTIFER_WEBSOCKET_PORT}:${NOTIFER_WEBSOCKET_PORT}
      - ${NOTIFER_PORT}:${NOTIFER_PORT}
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - UPDATE_DELAY=${WS_UPDATE_DELAY}
      - WS_PORT=${NOTIFER_WEBSOCKET_PORT}
      - EXPRESS_PORT=${NOTIFER_PORT}
    stdin_open: true
    tty: true

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - notifer

volumes:
  mongodb_data_container:
